name: Deploy-AWS-Frontend-Prod
on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_Upload:
    runs-on: ubuntu-latest
    outputs:
      ecrImage: ${{ steps.build-image.outputs.image }}
    steps:
    - name: Notify Slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        channel-id: C07VDG3H346
        payload: |
          {
            "text": "Build Status:",
            "attachments": [
              {
                "pretext": "Build started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-south-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: ECR Login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build Image (GITHUB_SHA)
      id: build-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: paydirectfrontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    - name: Notify Slack - Success
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      if:  ${{ success() }}
      with:
        # Unlike the step posting a new message, this step does not accept a channel name.
        # Please use a channel ID, not a name here.
        channel-id: "C07VDG3H346"
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "text": "Build Status:",
            "attachments": [
              {
                "pretext": "Build finished",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Completed"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    - name: Notify Slack - Failure
      uses: slackapi/slack-github-action@v1.27.0
      if:  ${{ failure() }}
      with:
        # Unlike the step posting a new message, this step does not accept a channel name.
        # Please use a channel ID, not a name here.
        channel-id: "C07VDG3H346"
        update-ts: ${{ steps.slack.outputs.ts }}
        payload: |
          {
            "text": "Build Status:",
            "attachments": [
              {
                "pretext": "Build failed",
                "color": "ff0000",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Failed"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  ECS_Deploy:
      needs: [Build_Upload]
      runs-on: ubuntu-latest
      steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: C07VDG3H346
          payload: |
            {
              "text": "Deployment Status:",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        env:
          CONTAINER_NAME: paydirect-frontend
          ECS_TASK_DEFINITION: TaskDefinitions/td-prod.json
        uses: aws-actions/amazon-ecs-render-task-definition@v1.6.0
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ needs.Build_Upload.outputs.ecrImage }}
      - name: Deploy Amazon ECS task definition
        env: 
          ECS_SERVICE: paydirect-portal-service-prod
          ECS_CLUSTER: Paydirect-Prod
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.1.2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
      - name: Notify Slack - Success
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        if:  ${{ success() }}
        with:
          # Unlike the step posting a new message, this step does not accept a channel name.
          # Please use a channel ID, not a name here.
          channel-id: "C07VDG3H346"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment Status:",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Notify Slack - Failure
        uses: slackapi/slack-github-action@v1.27.0
        if:  ${{ failure() }}
        with:
          # Unlike the step posting a new message, this step does not accept a channel name.
          # Please use a channel ID, not a name here.
          channel-id: "C07VDG3H346"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment Status:",
              "attachments": [
                {
                  "pretext": "Deployment failed",
                  "color": "ff0000",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
